# Generated by Django 4.1.6 on 2023-09-24 17:34

from django.conf import settings
import django.contrib.auth.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("email", models.CharField(default="", max_length=100, unique=True)),
                (
                    "username",
                    models.CharField(default="-", max_length=100, unique=True),
                ),
                (
                    "password1",
                    models.CharField(default="@Vidyasag1234", max_length=100),
                ),
                ("roll_num", models.CharField(default="", max_length=100)),
                ("is_sac", models.BooleanField(default=False)),
                ("is_admin", models.BooleanField(default=False)),
                ("is_faculty", models.BooleanField(default=False)),
                (
                    "phn_num",
                    models.CharField(default="+91 000 000 0000", max_length=17),
                ),
                (
                    "profile_pic",
                    models.ImageField(default="static/img.png", upload_to="uploads"),
                ),
                ("file_type", models.CharField(default="0", max_length=100)),
                ("bio", models.CharField(default="@", max_length=400)),
                ("sac_role", models.CharField(default="@", max_length=100)),
                ("admin_role", models.CharField(default="@", max_length=100)),
                ("faculty_role", models.CharField(default="@", max_length=100)),
                (
                    "date_of_birth",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("high_post_count", models.IntegerField(default=0)),
                ("high_lst_count", models.IntegerField(default=0)),
                ("branch", models.CharField(default="@", max_length=100)),
                ("batch", models.CharField(default="@", max_length=100)),
                ("year", models.IntegerField(default=0)),
                ("token", models.TextField(default="dfv", max_length=500)),
                ("platform", models.CharField(default="android", max_length=50)),
                (
                    "notif_settings",
                    models.CharField(default="111111111", max_length=100),
                ),
                ("notif_seen", models.BooleanField(default=True)),
                ("notif_count", models.IntegerField(default=0)),
                ("notif_ids", models.TextField(default="@")),
                ("domain", models.TextField(default="@nitc.ac.in")),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Academic_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("academic_name", models.CharField(default="", max_length=50)),
                ("domain", models.TextField(default="@nitc.ac.in")),
                ("sun", models.TextField(default="")),
                ("mon", models.TextField(default="")),
                ("tue", models.TextField(default="")),
                ("wed", models.TextField(default="")),
                ("thu", models.TextField(default="")),
                ("fri", models.TextField(default="")),
                ("sat", models.TextField(default="")),
            ],
        ),
        migrations.CreateModel(
            name="CalenderSub",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("sub_name", models.CharField(default="@", max_length=100)),
                ("sub_id", models.CharField(default="@", max_length=100)),
                ("all_years", models.TextField(default="@")),
                ("num_years", models.IntegerField(default=0)),
                ("description", models.TextField(default="@")),
                (
                    "posted_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("tot_ratings_val", models.IntegerField(default=0)),
                ("num_ratings", models.IntegerField(default=0)),
                ("domain", models.TextField(default="@nitc.ac.in")),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="CalenderSub_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-sub_name"],
            },
        ),
        migrations.CreateModel(
            name="Clubs_Sports",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "logo",
                    models.ImageField(
                        default="static/img.png", upload_to="club_sports"
                    ),
                ),
                ("title", models.CharField(default="", max_length=50)),
                ("club_r_sport", models.CharField(default="", max_length=50)),
                ("team_members", models.TextField(default="")),
                ("description", models.TextField(default="")),
                ("websites", models.CharField(default="", max_length=100)),
                ("sport_ground", models.TextField(default="")),
                (
                    "sport_ground_img",
                    models.ImageField(
                        default="static/img.png", upload_to="club_sports"
                    ),
                ),
                ("img_ratio", models.FloatField(default=1.0)),
                (
                    "date_of_join",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_like", models.BooleanField(default=False)),
                ("like_count", models.IntegerField(default=0)),
                ("domain", models.TextField(default="@nitc.ac.in")),
                (
                    "head",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Club_sports_head",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Club_sports_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-like_count", "-date_of_join"],
            },
        ),
        migrations.CreateModel(
            name="Lost_Found",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lst_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("title", models.CharField(default="", max_length=50)),
                ("description", models.TextField(default="")),
                ("tag", models.CharField(default="lost/found", max_length=50)),
                (
                    "img",
                    models.ImageField(default="static/img.png", upload_to="lost_found"),
                ),
                ("img_ratio", models.FloatField(default=1.0)),
                ("comment_count", models.IntegerField(default=0)),
                ("lst_hiders", models.TextField(default="")),
                (
                    "posted_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("domain", models.TextField(default="@nitc.ac.in")),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lst_found_username",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-posted_date"],
            },
        ),
        migrations.CreateModel(
            name="Mess_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("hostel", models.CharField(default="", max_length=50)),
                ("domain", models.TextField(default="@nitc.ac.in")),
                ("sun", models.TextField(default="")),
                ("mon", models.TextField(default="")),
                ("tue", models.TextField(default="")),
                ("wed", models.TextField(default="")),
                ("thu", models.TextField(default="")),
                ("fri", models.TextField(default="")),
                ("sat", models.TextField(default="")),
            ],
            options={
                "ordering": ["-hostel"],
            },
        ),
        migrations.CreateModel(
            name="Time_table",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("branch_name", models.CharField(default="", max_length=50)),
                (
                    "branch_tb_img",
                    models.ImageField(default="static/img.png", upload_to="time_table"),
                ),
                ("img_ratio", models.FloatField(default=1.0)),
                ("domain", models.TextField(default="@nitc.ac.in")),
                ("sun", models.TextField(default="")),
                ("mon", models.TextField(default="")),
                ("tue", models.TextField(default="")),
                ("wed", models.TextField(default="")),
                ("thu", models.TextField(default="")),
                ("fri", models.TextField(default="")),
                ("sat", models.TextField(default="")),
            ],
        ),
        migrations.CreateModel(
            name="Reports",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(default="")),
                ("report_belongs", models.CharField(default="student", max_length=100)),
                (
                    "posted_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("domain", models.TextField(default="@nitc.ac.in")),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="ReportUser",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ratings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(default="@")),
                ("rating", models.IntegerField(default=0)),
                ("verified", models.BooleanField(default=False)),
                (
                    "posted_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("domain", models.TextField(default="@nitc.ac.in")),
                (
                    "sub_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="CalenderSub_ratings",
                        to="api.calendersub",
                    ),
                ),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Ratings_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-posted_date"],
            },
        ),
        migrations.CreateModel(
            name="PostTable",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("post_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("title", models.CharField(default="", max_length=100)),
                ("description", models.TextField(default="")),
                ("img", models.FileField(default="static/img.png", upload_to="posts")),
                ("img_ratio", models.FloatField(default=1.0)),
                ("post_file", models.IntegerField(default=0)),
                ("tag", models.CharField(default="post", max_length=20)),
                ("is_like", models.BooleanField(default=False)),
                ("like_count", models.IntegerField(default=0)),
                ("comment_count", models.IntegerField(default=0)),
                ("post_hiders", models.TextField(default="")),
                (
                    "posted_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("event_date", models.DateTimeField(default=django.utils.timezone.now)),
                ("Admin", models.BooleanField(default=False)),
                ("domain", models.TextField(default="@nitc.ac.in")),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_table_username",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-posted_date"],
            },
        ),
        migrations.CreateModel(
            name="post_Likes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "posted_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("domain", models.TextField(default="@nitc.ac.in")),
                (
                    "post_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_like_id",
                        to="api.posttable",
                    ),
                ),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_like_username",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-posted_date"],
            },
        ),
        migrations.CreateModel(
            name="post_Comments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Comment", models.TextField(default="")),
                (
                    "posted_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("domain", models.TextField(default="@nitc.ac.in")),
                (
                    "post_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_comment",
                        to="api.posttable",
                    ),
                ),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="post_comment_username",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-posted_date"],
            },
        ),
        migrations.CreateModel(
            name="Notifications",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="", max_length=100)),
                ("description", models.TextField(default="")),
                ("branch", models.CharField(default="@", max_length=100)),
                (
                    "batch",
                    models.CharField(
                        default="CS@EC@EE@ME@CE@CH@BT@AR@MT@EP@PE", max_length=100
                    ),
                ),
                ("year", models.CharField(default="1111", max_length=100)),
                ("img", models.FileField(default="static/img.png", upload_to="notif")),
                ("img_ratio", models.FloatField(default=1.0)),
                (
                    "posted_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("domain", models.TextField(default="@nitc.ac.in")),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="Notification_username",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-posted_date"],
            },
        ),
        migrations.CreateModel(
            name="Messanger",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message_body", models.TextField(default="")),
                (
                    "message_file",
                    models.FileField(default="static/img.png", upload_to="messanger"),
                ),
                ("messag_file_type", models.CharField(default="@", max_length=100)),
                ("message_body_file", models.CharField(default="@", max_length=100)),
                ("message_replyto", models.TextField(default="@")),
                ("message_seen", models.BooleanField(default=False)),
                (
                    "message_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("domain", models.TextField(default="@nitc.ac.in")),
                (
                    "message_receiver",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_receiver",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "message_sender",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="message_sender",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-message_date"],
            },
        ),
        migrations.CreateModel(
            name="LST_Comments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("lst_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("Comment", models.TextField(default="")),
                (
                    "posted_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("domain", models.TextField(default="@nitc.ac.in")),
                (
                    "lst_cmnt_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lst_found_comment",
                        to="api.lost_found",
                    ),
                ),
                (
                    "username",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="lst_cmnt_username",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-posted_date"],
            },
        ),
        migrations.CreateModel(
            name="Events",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("title", models.CharField(default="", max_length=50)),
                ("description", models.TextField(default="")),
                (
                    "event_img",
                    models.FileField(default="static/img.png", upload_to="events"),
                ),
                ("img_ratio", models.FloatField(default=1.0)),
                (
                    "event_vedio",
                    models.FileField(default="static/img.png", upload_to="pics"),
                ),
                ("vedio_ratio", models.FloatField(default=1.0)),
                ("event_updates", models.TextField(default="updates")),
                ("is_like", models.BooleanField(default=False)),
                ("like_count", models.IntegerField(default=0)),
                ("event_date", models.DateTimeField(default="2023-06-30T08:23:17Z")),
                (
                    "posted_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("domain", models.TextField(default="@nitc.ac.in")),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events_username",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-posted_date"],
            },
        ),
        migrations.CreateModel(
            name="Event_likes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "posted_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("domain", models.TextField(default="@nitc.ac.in")),
                (
                    "event_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_like_id",
                        to="api.events",
                    ),
                ),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_like",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-posted_date"],
            },
        ),
        migrations.CreateModel(
            name="Clubs_Sports_likes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "posted_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("domain", models.TextField(default="@nitc.ac.in")),
                (
                    "club_sport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="club_sport_like_id",
                        to="api.clubs_sports",
                    ),
                ),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="club_sport_like",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-posted_date"],
            },
        ),
        migrations.CreateModel(
            name="CalenderSubYears",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year_name", models.CharField(default="@", max_length=100)),
                ("private", models.BooleanField(default=False)),
                ("num_files", models.IntegerField(default=0)),
                ("description", models.TextField(default="@")),
                (
                    "posted_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("domain", models.TextField(default="@nitc.ac.in")),
                (
                    "sub_name",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="CalenderSub",
                        to="api.calendersub",
                    ),
                ),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="CalenderSubYears_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-year_name"],
            },
        ),
        migrations.CreateModel(
            name="CalenderSubFiles",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField(default="@")),
                (
                    "qn_ans_file",
                    models.FileField(default="static/img.png", upload_to="QnsAns"),
                ),
                ("file_type", models.CharField(default="@", max_length=100)),
                ("file_name", models.CharField(default="@", max_length=100)),
                ("year", models.CharField(default="@", max_length=100)),
                (
                    "posted_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("domain", models.TextField(default="@nitc.ac.in")),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="CalenderSubFiles_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "year_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="CalenderSubYears",
                        to="api.calendersubyears",
                    ),
                ),
            ],
            options={
                "ordering": ["-file_name"],
            },
        ),
        migrations.CreateModel(
            name="CalenderEvents",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("cal_event_type", models.CharField(default="self", max_length=100)),
                ("title", models.CharField(default="", max_length=100)),
                ("description", models.TextField(default="")),
                (
                    "calender_date_file",
                    models.FileField(default="static/img.png", upload_to="cal_events"),
                ),
                ("file_type", models.CharField(default="@", max_length=100)),
                ("branch", models.CharField(default="@", max_length=100)),
                ("year", models.CharField(default="@", max_length=100)),
                ("event_date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "posted_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("domain", models.TextField(default="@nitc.ac.in")),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="CalenderEvent_user",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-posted_date"],
            },
        ),
        migrations.CreateModel(
            name="Alerts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alert_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("title", models.CharField(default="", max_length=50)),
                ("description", models.TextField(default="")),
                ("img", models.FileField(default="static/img.png", upload_to="alerts")),
                ("img_ratio", models.FloatField(default=0.0)),
                ("comment_count", models.IntegerField(default=0)),
                (
                    "allow_branchs",
                    models.CharField(
                        default="CS@EC@EE@ME@CE@CH@BT@AR@MT@EP@PE", max_length=100
                    ),
                ),
                ("allow_years", models.CharField(default="1111", max_length=100)),
                (
                    "posted_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("domain", models.TextField(default="@nitc.ac.in")),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alerts_username",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-posted_date"],
            },
        ),
        migrations.CreateModel(
            name="ALERT_Comments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("alert_id", models.UUIDField(default=uuid.uuid4, editable=False)),
                ("Comment", models.TextField(default="")),
                ("img", models.FileField(default="static/img.png", upload_to="alerts")),
                ("img_ratio", models.FloatField(default=0.0)),
                (
                    "allow_branchs",
                    models.CharField(
                        default="CS@EC@EE@ME@CE@CH@BT@AR@MT@EP@PE", max_length=100
                    ),
                ),
                ("allow_years", models.CharField(default="1111", max_length=100)),
                (
                    "posted_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("domain", models.TextField(default="@nitc.ac.in")),
                (
                    "alert_cmnt_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_comment",
                        to="api.alerts",
                    ),
                ),
                (
                    "username",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="alert_cmnt_username",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-posted_date"],
            },
        ),
    ]
