# Generated by Django 4.1.6 on 2023-09-24 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="notif_settings",
            field=models.CharField(default="11111111111111111111111", max_length=100),
        ),
    ]
