# Generated by Django 4.1.6 on 2023-09-24 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_user_notif_settings"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="domain",
        ),
        migrations.RemoveField(
            model_name="user",
            name="notif_settings",
        ),
    ]
