# Generated by Django 4.1.6 on 2023-09-24 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0003_remove_user_domain_remove_user_notif_settings"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="domain",
            field=models.CharField(default="@nitc.ac.in", max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="notif_settings",
            field=models.CharField(default="11111111111111111111111", max_length=100),
        ),
    ]
