# Generated by Django 4.1.6 on 2023-09-28 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0005_rename_is_sac_user_is_student_admin_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="course",
            field=models.CharField(default="B.TECH", max_length=100),
        ),
        migrations.AddField(
            model_name="user",
            name="is_details",
            field=models.BooleanField(default=False),
        ),
    ]
