# Generated by Django 4.1.6 on 2023-10-11 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0007_alert_comments_all_universities_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="alert_comments",
            name="all_universities",
        ),
    ]
