# Generated by Django 4.1.6 on 2023-02-27 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_time_table_branch_tb_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='alerts',
            name='img_ratio',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='clubs_sports',
            name='sport_ground',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='clubs_sports',
            name='sport_ground_img',
            field=models.ImageField(default='static/img.png', upload_to='pics'),
        ),
        migrations.AddField(
            model_name='clubs_sports',
            name='sport_ground_img_ratio',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='events',
            name='event_img_ratio',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='events',
            name='event_vedio_ratio',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='lost_found',
            name='img_ratio',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='posttable',
            name='img_ratio',
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name='time_table',
            name='branch_tb_img_ration',
            field=models.FloatField(default=1.0),
        ),
    ]
