# Generated by Django 4.1.6 on 2023-03-02 13:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alerts_img_ratio_clubs_sports_sport_ground_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clubs_sports',
            old_name='sport_ground_img_ratio',
            new_name='img_ratio',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='event_img_ratio',
            new_name='img_ratio',
        ),
        migrations.RenameField(
            model_name='events',
            old_name='event_vedio_ratio',
            new_name='vedio_ratio',
        ),
        migrations.RenameField(
            model_name='time_table',
            old_name='branch_tb_img_ration',
            new_name='img_ratio',
        ),
    ]
