# Generated by Django 4.1.6 on 2023-10-12 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0011_alter_unibranches_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="branchsub",
            name="course",
            field=models.CharField(
                choices=[
                    ("B.Tech", "B.Tech"),
                    ("M.Tech", "M.Tech"),
                    ("PG", "PG"),
                    ("Phd", "Phd"),
                    ("MBA", "MBA"),
                ],
                default="B.Tech",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="branchsubfiles",
            name="course",
            field=models.CharField(
                choices=[
                    ("B.Tech", "B.Tech"),
                    ("M.Tech", "M.Tech"),
                    ("PG", "PG"),
                    ("Phd", "Phd"),
                    ("MBA", "MBA"),
                ],
                default="B.Tech",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="branchsubyears",
            name="course",
            field=models.CharField(
                choices=[
                    ("B.Tech", "B.Tech"),
                    ("M.Tech", "M.Tech"),
                    ("PG", "PG"),
                    ("Phd", "Phd"),
                    ("MBA", "MBA"),
                ],
                default="B.Tech",
                max_length=100,
            ),
        ),
        migrations.AlterField(
            model_name="unibranches",
            name="course",
            field=models.CharField(
                choices=[
                    ("B.Tech", "B.Tech"),
                    ("M.Tech", "M.Tech"),
                    ("PG", "PG"),
                    ("Phd", "Phd"),
                    ("MBA", "MBA"),
                ],
                default="B.Tech",
                max_length=100,
            ),
        ),
    ]
