# Generated by Django 4.1.6 on 2023-10-16 14:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0017_rename_high_lst_count_user_lst_count_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="clubs",
            new_name="clz_clubs",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="fests",
            new_name="clz_fests",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="sac",
            new_name="clz_sacs",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="clz_sac_head",
            new_name="clz_sacs_head",
        ),
        migrations.RenameField(
            model_name="user",
            old_name="sports",
            new_name="clz_sports",
        ),
    ]
