# Generated by Django 4.1.6 on 2023-10-16 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0019_alter_user_clz_clubs_alter_user_clz_fests_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="clz_clubs",
        ),
        migrations.RemoveField(
            model_name="user",
            name="clz_fests",
        ),
        migrations.RemoveField(
            model_name="user",
            name="clz_sacs",
        ),
        migrations.RemoveField(
            model_name="user",
            name="clz_sports",
        ),
    ]
