# Generated by Django 4.1.6 on 2023-10-16 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api2", "0006_alter_sac_mems_options_sac_mems_date_of_join"),
        ("api", "0021_user_clz_clubs_user_clz_fests_user_clz_sacs_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="posttable",
            name="club_post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_from_club",
                to="api2.allclubs",
            ),
        ),
    ]
