# Generated by Django 4.1.6 on 2023-10-16 18:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api2", "0006_alter_sac_mems_options_sac_mems_date_of_join"),
        ("api", "0022_posttable_club_post"),
    ]

    operations = [
        migrations.AddField(
            model_name="alerts",
            name="club_thread",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="thread_from_club",
                to="api2.allclubs",
            ),
        ),
        migrations.AddField(
            model_name="alerts",
            name="fest_thread",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="thread_from_club",
                to="api2.allfests",
            ),
        ),
        migrations.AddField(
            model_name="alerts",
            name="sac_thread",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="thread_from_club",
                to="api2.sac_mems",
            ),
        ),
        migrations.AddField(
            model_name="alerts",
            name="sport_thread",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="thread_from_club",
                to="api2.allsports",
            ),
        ),
        migrations.AddField(
            model_name="alerts",
            name="thread_category",
            field=models.CharField(
                choices=[
                    ("student", "student"),
                    ("club", "club"),
                    ("sport", "sport"),
                    ("fest", "fest"),
                    ("sac", "sac"),
                ],
                default="student",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="events",
            name="club_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_from_club",
                to="api2.allclubs",
            ),
        ),
        migrations.AddField(
            model_name="events",
            name="event_category",
            field=models.CharField(
                choices=[
                    ("student", "student"),
                    ("club", "club"),
                    ("sport", "sport"),
                    ("fest", "fest"),
                    ("sac", "sac"),
                ],
                default="student",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="events",
            name="fest_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_from_club",
                to="api2.allfests",
            ),
        ),
        migrations.AddField(
            model_name="events",
            name="sac_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_from_club",
                to="api2.sac_mems",
            ),
        ),
        migrations.AddField(
            model_name="events",
            name="sport_event",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_from_club",
                to="api2.allsports",
            ),
        ),
        migrations.AddField(
            model_name="posttable",
            name="fest_post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_from_club",
                to="api2.allfests",
            ),
        ),
        migrations.AddField(
            model_name="posttable",
            name="post_category",
            field=models.CharField(
                choices=[
                    ("student", "student"),
                    ("club", "club"),
                    ("sport", "sport"),
                    ("fest", "fest"),
                    ("sac", "sac"),
                ],
                default="student",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="posttable",
            name="sac_post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_from_club",
                to="api2.sac_mems",
            ),
        ),
        migrations.AddField(
            model_name="posttable",
            name="sport_post",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_from_club",
                to="api2.allsports",
            ),
        ),
    ]
