# Generated by Django 4.1.6 on 2023-10-17 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0023_alerts_club_thread_alerts_fest_thread_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="clz_users_head",
            field=models.BooleanField(default=False),
        ),
    ]
