# Generated by Django 4.1.6 on 2023-10-18 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0024_user_clz_users_head"),
    ]

    operations = [
        migrations.RenameField(
            model_name="alerts",
            old_name="thread_category",
            new_name="category",
        ),
        migrations.RenameField(
            model_name="alerts",
            old_name="club_thread",
            new_name="club",
        ),
        migrations.RenameField(
            model_name="alerts",
            old_name="fest_thread",
            new_name="fest",
        ),
        migrations.RenameField(
            model_name="alerts",
            old_name="sac_thread",
            new_name="sac",
        ),
        migrations.RenameField(
            model_name="alerts",
            old_name="sport_thread",
            new_name="sport",
        ),
        migrations.RenameField(
            model_name="events",
            old_name="event_category",
            new_name="category",
        ),
        migrations.RenameField(
            model_name="events",
            old_name="club_event",
            new_name="club",
        ),
        migrations.RenameField(
            model_name="events",
            old_name="fest_event",
            new_name="fest",
        ),
        migrations.RenameField(
            model_name="events",
            old_name="sac_event",
            new_name="sac",
        ),
        migrations.RenameField(
            model_name="events",
            old_name="sport_event",
            new_name="sport",
        ),
        migrations.RenameField(
            model_name="posttable",
            old_name="post_category",
            new_name="category",
        ),
        migrations.RenameField(
            model_name="posttable",
            old_name="club_post",
            new_name="club",
        ),
        migrations.RenameField(
            model_name="posttable",
            old_name="fest_post",
            new_name="fest",
        ),
        migrations.RenameField(
            model_name="posttable",
            old_name="sac_post",
            new_name="sac",
        ),
        migrations.RenameField(
            model_name="posttable",
            old_name="sport_post",
            new_name="sport",
        ),
    ]
