# Generated by Django 4.1.6 on 2023-10-20 12:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api2", "0007_allclubs_star_mark_allfests_star_mark_and_more"),
        ("api", "0027_alter_user_update_mark"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alerts",
            name="fest",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="thread_from_fest",
                to="api2.allfests",
            ),
        ),
        migrations.AlterField(
            model_name="alerts",
            name="sac",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="thread_from_sac",
                to="api2.sac_mems",
            ),
        ),
        migrations.AlterField(
            model_name="alerts",
            name="sport",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="thread_from_sport",
                to="api2.allsports",
            ),
        ),
        migrations.AlterField(
            model_name="events",
            name="fest",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_from_fest",
                to="api2.allfests",
            ),
        ),
        migrations.AlterField(
            model_name="events",
            name="sac",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_from_sac",
                to="api2.sac_mems",
            ),
        ),
        migrations.AlterField(
            model_name="events",
            name="sport",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_from_sport",
                to="api2.allsports",
            ),
        ),
        migrations.AlterField(
            model_name="posttable",
            name="fest",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_from_fest",
                to="api2.allfests",
            ),
        ),
        migrations.AlterField(
            model_name="posttable",
            name="sac",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_from_sac",
                to="api2.sac_mems",
            ),
        ),
        migrations.AlterField(
            model_name="posttable",
            name="sport",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="post_from_sport",
                to="api2.allsports",
            ),
        ),
    ]
