# Generated by Django 4.1.6 on 2023-10-21 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0028_alter_alerts_fest_alter_alerts_sac_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="buy_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="user",
            name="thread_count",
            field=models.IntegerField(default=0),
        ),
    ]
