# Generated by Django 4.1.6 on 2023-10-22 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0029_user_buy_count_user_thread_count"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alert_comments",
            name="img",
            field=models.FileField(default="static/img.png", upload_to="pg"),
        ),
        migrations.AlterField(
            model_name="alerts",
            name="img",
            field=models.FileField(default="static/img.png", upload_to="pg"),
        ),
        migrations.AlterField(
            model_name="branchsubfiles",
            name="qn_ans_file",
            field=models.FileField(default="static/img.png", upload_to="pg"),
        ),
        migrations.AlterField(
            model_name="calenderevents",
            name="calender_date_file",
            field=models.FileField(default="static/img.png", upload_to="pg"),
        ),
        migrations.AlterField(
            model_name="events",
            name="event_img",
            field=models.FileField(default="static/img.png", upload_to="pg"),
        ),
        migrations.AlterField(
            model_name="events",
            name="event_vedio",
            field=models.FileField(default="static/img.png", upload_to="pg"),
        ),
        migrations.AlterField(
            model_name="lost_found",
            name="img",
            field=models.ImageField(default="static/img.png", upload_to="pg"),
        ),
        migrations.AlterField(
            model_name="messanger",
            name="message_file",
            field=models.FileField(default="static/img.png", upload_to="pg"),
        ),
        migrations.AlterField(
            model_name="posttable",
            name="img",
            field=models.FileField(default="static/img.png", upload_to="pg"),
        ),
        migrations.AlterField(
            model_name="time_table",
            name="branch_tb_img",
            field=models.ImageField(default="static/img.png", upload_to="pg"),
        ),
        migrations.AlterField(
            model_name="user",
            name="profile_pic",
            field=models.ImageField(default="static/img.png", upload_to="pg"),
        ),
    ]
