# Generated by Django 4.1.6 on 2023-10-24 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0031_filternotifications"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="filternotifications",
            name="username",
        ),
    ]
