# Generated by Django 4.1.6 on 2023-10-24 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0032_remove_filternotifications_username"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FilterNotifications",
        ),
    ]
