# Generated by Django 4.1.6 on 2023-10-25 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0034_filternotifications"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="filternotifications",
            options={"ordering": ["-username"]},
        ),
        migrations.AddField(
            model_name="filternotifications",
            name="domain",
            field=models.TextField(default="@nitc.ac.in"),
        ),
    ]
