# Generated by Django 4.1.6 on 2023-10-31 16:18

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0035_alter_filternotifications_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
