# Generated by Django 4.1.6 on 2023-10-31 16:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0036_user_user_uuid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="user_uuid",
            field=models.UUIDField(default=uuid.uuid4),
        ),
    ]
