# Generated by Django 4.1.6 on 2023-11-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0037_alter_user_user_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="calenderevents",
            name="all_universities",
            field=models.BooleanField(default=True),
        ),
    ]
