# Generated by Django 4.1.6 on 2023-11-10 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0038_calenderevents_all_universities"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="is_placement_admin",
            field=models.BooleanField(default=False),
        ),
    ]
