# Generated by Django 4.1.6 on 2023-11-11 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0039_user_is_placement_admin"),
    ]

    operations = [
        migrations.AddField(
            model_name="branchsub",
            name="InternCompany",
            field=models.BooleanField(default=False),
        ),
    ]
