# Generated by Django 4.1.6 on 2023-11-15 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0040_branchsub_interncompany"),
    ]

    operations = [
        migrations.AddField(
            model_name="lost_found",
            name="category",
            field=models.CharField(
                choices=[
                    ("cards", "cards"),
                    ("essentials", "essentials"),
                    ("smartDevices", "smartDevices"),
                    ("belongings", "belongings"),
                    ("valuables", "valuables"),
                    ("clothings", "clothings"),
                    ("rideShares", "rideShares"),
                    ("usedCampusItems", "usedCampusItems"),
                    ("houseSharings", "houseSharings"),
                    ("others", "others"),
                ],
                default="belongings",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="lost_found",
            name="price",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="lost_found",
            name="tag",
            field=models.CharField(
                choices=[
                    ("lost", "lost"),
                    ("found", "found"),
                    ("buy", "buy"),
                    ("sell", "sell"),
                ],
                default="lost",
                max_length=50,
            ),
        ),
    ]
