# Generated by Django 4.1.6 on 2023-11-26 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0043_alter_user_update_mark"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="course",
            field=models.CharField(default="B.Tech", max_length=100),
        ),
    ]
