# Generated by Django 4.1.6 on 2023-11-27 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0044_alter_user_course"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="dating_profile",
            field=models.BooleanField(default=False),
        ),
    ]
