# Generated by Django 4.1.6 on 2023-11-28 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0045_user_dating_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="alerts",
            name="allow_courses",
            field=models.CharField(
                default="B.Tech@M.Tech@PG@Phd@MBA@Other", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="calenderevents",
            name="course",
            field=models.CharField(default="@", max_length=100),
        ),
        migrations.AlterField(
            model_name="alerts",
            name="allow_branchs",
            field=models.CharField(
                default="CS@EC@EE@ME@CE@CH@BT@AR@MT@EP@PE@Other", max_length=100
            ),
        ),
    ]
