# Generated by Django 4.1.6 on 2023-11-29 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0046_alerts_allow_courses_calenderevents_course_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="alerts",
            name="algoValue",
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name="events",
            name="algoValue",
            field=models.FloatField(default=1.0),
        ),
        migrations.AddField(
            model_name="posttable",
            name="algoValue",
            field=models.FloatField(default=1.0),
        ),
    ]
