# Generated by Django 4.1.6 on 2023-11-30 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0047_alerts_algovalue_events_algovalue_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="posttable",
            options={"ordering": ["-algoValue"]},
        ),
    ]
