# Generated by Django 4.1.6 on 2023-12-01 00:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0051_alter_user_update_mark"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="update_mark",
        ),
    ]
