# Generated by Django 4.1.6 on 2023-12-01 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0052_remove_user_update_mark"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="update_mark",
            field=models.CharField(default="instabook3", max_length=11),
        ),
    ]
