# Generated by Django 4.1.6 on 2023-12-01 02:01

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0053_user_update_mark"),
    ]

    operations = [
        migrations.CreateModel(
            name="Buy_Sell",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(default="", max_length=50)),
                ("description", models.TextField(default="")),
                (
                    "tag",
                    models.CharField(
                        choices=[
                            ("lost", "lost"),
                            ("found", "found"),
                            ("buy", "buy"),
                            ("sell", "sell"),
                        ],
                        default="lost",
                        max_length=50,
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("all", "all"),
                            ("cards", "cards"),
                            ("essentials", "essentials"),
                            ("smartDevices", "smartDevices"),
                            ("belongings", "belongings"),
                            ("valuables", "valuables"),
                            ("clothings", "clothings"),
                            ("rideShares", "rideShares"),
                            ("usedCampusItems", "usedCampusItems"),
                            ("houseSharings", "houseSharings"),
                            ("others", "others"),
                        ],
                        default="belongings",
                        max_length=50,
                    ),
                ),
                ("price", models.IntegerField(default=0)),
                ("img", models.ImageField(default="static/img.png", upload_to="pg")),
                ("img_ratio", models.FloatField(default=1.0)),
                ("comment_count", models.IntegerField(default=0)),
                ("lst_hiders", models.TextField(default="")),
                ("posted_date", models.DateTimeField(default=datetime.datetime.now)),
                ("domain", models.TextField(default="@nitc.ac.in")),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buy_sell_username",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-posted_date"],
            },
        ),
        migrations.CreateModel(
            name="BS_Comments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Comment", models.TextField(default="")),
                ("posted_date", models.DateTimeField(default=datetime.datetime.now)),
                ("domain", models.TextField(default="@nitc.ac.in")),
                (
                    "BS_cmnt_id",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="buy_sell_comment",
                        to="api.lost_found",
                    ),
                ),
                (
                    "username",
                    models.ForeignKey(
                        default="",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bs_cmnt_username",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-posted_date"],
            },
        ),
    ]
