# Generated by Django 4.1.6 on 2023-12-01 02:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0055_rename_bs_cmnt_id_bs_comments_bs_cmnt_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="bs_comments",
            name="bs_cmnt_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="buy_sell_comment",
                to="api.buy_sell",
            ),
        ),
    ]
