# Generated by Django 4.1.6 on 2023-12-04 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0058_alter_user_phn_num"),
    ]

    operations = [
        migrations.AlterField(
            model_name="alerts",
            name="allow_courses",
            field=models.CharField(
                default="B.Tech@M.Tech@PG@Phd@MBA@Other@B.Arch", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="alerts",
            name="allow_years",
            field=models.CharField(default="11111", max_length=100),
        ),
    ]
