# Generated by Django 4.1.6 on 2023-12-04 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0059_alter_alerts_allow_courses_alter_alerts_allow_years"),
    ]

    operations = [
        migrations.AddField(
            model_name="branchsub",
            name="PlacementCompany",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="branchsubyears",
            name="InternCompany",
            field=models.BooleanField(default=False),
        ),
    ]
