# Generated by Django 4.1.6 on 2023-12-09 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0061_remove_calenderevents_course_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="calenderevents",
            name="course",
            field=models.CharField(
                default="B.Tech@M.Tech@PG@Phd@MBA@Other@B.Arch", max_length=100
            ),
        ),
    ]
