# Generated by Django 4.1.6 on 2023-12-21 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0062_calenderevents_course"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="calenderevents",
            name="branch",
        ),
        migrations.RemoveField(
            model_name="calenderevents",
            name="course",
        ),
        migrations.RemoveField(
            model_name="calenderevents",
            name="year",
        ),
    ]
