# Generated by Django 4.1.6 on 2024-01-04 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0064_calenderevents_branch_calenderevents_course_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="branchsubfiles",
            options={"ordering": ["-username"]},
        ),
        migrations.AlterModelOptions(
            name="branchsubyears",
            options={"ordering": ["-sub_name"]},
        ),
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(default="-", max_length=100),
        ),
    ]
