# Generated by Django 4.1.6 on 2024-02-11 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0066_universities'),
    ]

    operations = [
        migrations.AddField(
            model_name='universities',
            name='domain',
            field=models.TextField(default='@nitc.ac.in'),
        ),
    ]
