# Generated by Django 4.1.6 on 2024-02-11 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0067_universities_domain'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Universities',
        ),
    ]
