# Generated by Django 4.1.6 on 2024-02-11 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0069_universities'),
    ]

    operations = [
        migrations.AddField(
            model_name='universities',
            name='univPicRatio',
            field=models.IntegerField(default=0),
        ),
    ]
