# Generated by Django 4.1.6 on 2024-02-16 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0070_universities_univpicratio'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='universities',
            options={'ordering': ['-joinedDate']},
        ),
        migrations.AddField(
            model_name='universities',
            name='Rating',
            field=models.FloatField(default=4.0),
        ),
        migrations.AddField(
            model_name='universities',
            name='about',
            field=models.TextField(default='Not Updated'),
        ),
        migrations.AddField(
            model_name='universities',
            name='courses',
            field=models.TextField(default='Not Updated'),
        ),
        migrations.AddField(
            model_name='universities',
            name='fees',
            field=models.TextField(default='Not Updated'),
        ),
        migrations.AddField(
            model_name='universities',
            name='hostels',
            field=models.TextField(default='Not Updated'),
        ),
        migrations.AddField(
            model_name='universities',
            name='placements',
            field=models.TextField(default='Not Updated'),
        ),
        migrations.AddField(
            model_name='universities',
            name='totalRatings',
            field=models.IntegerField(default=100),
        ),
    ]
