# Generated by Django 4.1.6 on 2023-10-15 02:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AllClubs",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=50)),
                (
                    "logo",
                    models.ImageField(
                        default="static/img.png", upload_to="club_sports"
                    ),
                ),
                ("title", models.CharField(default="", max_length=50)),
                ("team_members", models.TextField(default="")),
                ("description", models.TextField(default="")),
                ("websites", models.CharField(default="", max_length=100)),
                (
                    "date_of_join",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_like", models.BooleanField(default=False)),
                ("like_count", models.IntegerField(default=0)),
                ("domain", models.TextField(default="@nitc.ac.in")),
                (
                    "head",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="AllClubs_head",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-like_count", "-date_of_join"],
            },
        ),
        migrations.CreateModel(
            name="AllFests",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=50)),
                (
                    "logo",
                    models.ImageField(
                        default="static/img.png", upload_to="club_sports"
                    ),
                ),
                ("title", models.CharField(default="", max_length=50)),
                ("team_members", models.TextField(default="")),
                ("description", models.TextField(default="")),
                ("websites", models.CharField(default="", max_length=100)),
                ("sport_ground", models.TextField(default="")),
                ("is_like", models.BooleanField(default=False)),
                ("like_count", models.IntegerField(default=0)),
                (
                    "date_of_join",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("domain", models.TextField(default="@nitc.ac.in")),
                (
                    "head",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="AllFests_head",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-like_count", "-date_of_join"],
            },
        ),
        migrations.CreateModel(
            name="AllSports",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(default="", max_length=50)),
                (
                    "logo",
                    models.ImageField(
                        default="static/img.png", upload_to="club_sports"
                    ),
                ),
                ("title", models.CharField(default="", max_length=50)),
                ("team_members", models.TextField(default="")),
                ("description", models.TextField(default="")),
                ("websites", models.CharField(default="", max_length=100)),
                ("sport_ground", models.TextField(default="")),
                (
                    "sport_ground_img",
                    models.ImageField(
                        default="static/img.png", upload_to="club_sports"
                    ),
                ),
                ("img_ratio", models.FloatField(default=1.0)),
                (
                    "date_of_join",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("is_like", models.BooleanField(default=False)),
                ("like_count", models.IntegerField(default=0)),
                ("domain", models.TextField(default="@nitc.ac.in")),
                (
                    "head",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="AllSports_head",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-like_count", "-date_of_join"],
            },
        ),
        migrations.CreateModel(
            name="Sports_likes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "posted_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("domain", models.TextField(default="@nitc.ac.in")),
                (
                    "sport",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="AllSports_like_id",
                        to="api2.allsports",
                    ),
                ),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="AllSports_like",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-posted_date"],
            },
        ),
        migrations.CreateModel(
            name="Fests_likes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "posted_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("domain", models.TextField(default="@nitc.ac.in")),
                (
                    "fest",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="AllFests_like_id",
                        to="api2.allfests",
                    ),
                ),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="AllFests_like",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-posted_date"],
            },
        ),
        migrations.CreateModel(
            name="Clubs_likes",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "posted_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                ("domain", models.TextField(default="@nitc.ac.in")),
                (
                    "club",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="AllClubs_like_id",
                        to="api2.allclubs",
                    ),
                ),
                (
                    "username",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="AllClubs_like",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-posted_date"],
            },
        ),
    ]
