# Generated by Django 4.1.6 on 2023-10-15 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("api2", "0002_reports_notifications"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="allfests",
            name="sport_ground",
        ),
    ]
