# Generated by Django 4.1.6 on 2023-10-15 17:27

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api2", "0005_sac_mems_domain"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="sac_mems",
            options={"ordering": ["-date_of_join"]},
        ),
        migrations.AddField(
            model_name="sac_mems",
            name="date_of_join",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
