# Generated by Django 4.1.6 on 2023-10-17 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api2", "0006_alter_sac_mems_options_sac_mems_date_of_join"),
    ]

    operations = [
        migrations.AddField(
            model_name="allclubs",
            name="star_mark",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="allfests",
            name="star_mark",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="allsports",
            name="star_mark",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="sac_mems",
            name="star_mark",
            field=models.IntegerField(default=0),
        ),
    ]
