# Generated by Django 4.1.6 on 2023-10-21 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api2", "0007_allclubs_star_mark_allfests_star_mark_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="allclubs",
            name="activity_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="allclubs",
            name="post_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="allclubs",
            name="thread_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="allfests",
            name="activity_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="allfests",
            name="post_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="allfests",
            name="thread_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="allsports",
            name="activity_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="allsports",
            name="post_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="allsports",
            name="thread_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="sac_mems",
            name="activity_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="sac_mems",
            name="post_count",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="sac_mems",
            name="thread_count",
            field=models.IntegerField(default=0),
        ),
    ]
