# Generated by Django 4.1.6 on 2023-10-22 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api2", "0008_allclubs_activity_count_allclubs_post_count_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allclubs",
            name="logo",
            field=models.ImageField(default="static/img.png", upload_to="pg"),
        ),
        migrations.AlterField(
            model_name="allfests",
            name="logo",
            field=models.ImageField(default="static/img.png", upload_to="pg"),
        ),
        migrations.AlterField(
            model_name="allsports",
            name="logo",
            field=models.ImageField(default="static/img.png", upload_to="pg"),
        ),
        migrations.AlterField(
            model_name="allsports",
            name="sport_ground_img",
            field=models.ImageField(default="static/img.png", upload_to="pg"),
        ),
        migrations.AlterField(
            model_name="notifications",
            name="img",
            field=models.FileField(default="static/img.png", upload_to="pg"),
        ),
        migrations.AlterField(
            model_name="sac_mems",
            name="logo",
            field=models.ImageField(default="static/img.png", upload_to="pg"),
        ),
    ]
