# Generated by Django 4.1.6 on 2023-11-15 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api2", "0009_alter_allclubs_logo_alter_allfests_logo_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="notifications",
            name="onlyUsername",
            field=models.BooleanField(default=False),
        ),
    ]
