# Generated by Django 4.1.6 on 2023-11-26 14:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api2", "0010_notifications_onlyusername"),
    ]

    operations = [
        migrations.CreateModel(
            name="DatingUser",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("dummyUserUuid", models.UUIDField(default=uuid.uuid4)),
                ("dummyName", models.CharField(default="student", max_length=100)),
                (
                    "dummyProfile",
                    models.FileField(default="static/img.png", upload_to="pg"),
                ),
                ("dummyBio", models.TextField(default="")),
                ("dummyDomain", models.TextField(default="@nitc.ac.in")),
                ("connections", models.IntegerField(default=0)),
                ("domain", models.TextField(default="@nitc.ac.in")),
                (
                    "username",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="DatingUser",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
