# Generated by Django 4.1.6 on 2023-11-26 15:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("api2", "0011_datinguser"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="datinguser",
            options={"ordering": ["-posted_date"]},
        ),
        migrations.AddField(
            model_name="datinguser",
            name="posted_date",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
