# Generated by Django 4.1.6 on 2023-11-28 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api2", "0013_notifications_course"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datinguser",
            name="posted_date",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
