# Generated by Django 4.1.6 on 2023-11-28 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api2", "0014_alter_datinguser_posted_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="datinguser",
            name="numChats",
            field=models.IntegerField(default=0),
        ),
    ]
