# Generated by Django 4.1.6 on 2023-11-29 13:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("api2", "0015_datinguser_numchats"),
    ]

    operations = [
        migrations.CreateModel(
            name="DatingUserReactions",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Reaction", models.IntegerField(default=0)),
                (
                    "posted_date",
                    models.DateTimeField(default=django.utils.timezone.now),
                ),
                (
                    "DatingUser",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="DatingUserReactions",
                        to="api2.datinguser",
                    ),
                ),
                (
                    "username",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="DatingUserReactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-posted_date"],
            },
        ),
    ]
