# Generated by Django 4.1.6 on 2023-11-29 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api2", "0016_datinguserreactions"),
    ]

    operations = [
        migrations.AddField(
            model_name="datinguser",
            name="Reactions",
            field=models.IntegerField(default=0),
        ),
    ]
