# Generated by Django 4.1.6 on 2023-11-29 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api2", "0017_datinguser_reactions"),
    ]

    operations = [
        migrations.AddField(
            model_name="datinguser",
            name="is_reaction",
            field=models.IntegerField(default=0),
        ),
    ]
