# Generated by Django 4.1.6 on 2023-11-29 19:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api2", "0020_datinguser_algovalue"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="datinguser",
            options={"ordering": ["-algoValue"]},
        ),
        migrations.AlterField(
            model_name="datinguser",
            name="posted_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 29, 19, 34, 27, 78011)
            ),
        ),
    ]
