# Generated by Django 4.1.6 on 2023-11-30 14:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api2", "0022_alter_datinguser_posted_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="allclubs",
            name="date_of_join",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="allfests",
            name="date_of_join",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="allsports",
            name="date_of_join",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="clubs_likes",
            name="posted_date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="datinguser",
            name="posted_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 11, 30, 14, 50, 40, 499533)
            ),
        ),
        migrations.AlterField(
            model_name="fests_likes",
            name="posted_date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="notifications",
            name="posted_date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="reports",
            name="posted_date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="sac_mems",
            name="date_of_join",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name="sports_likes",
            name="posted_date",
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
