# Generated by Django 4.1.6 on 2023-12-04 01:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api2", "0033_alter_datinguser_posted_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datinguser",
            name="posted_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 4, 1, 16, 47, 888914)
            ),
        ),
        migrations.AlterField(
            model_name="notifications",
            name="course",
            field=models.CharField(
                default="B.Tech@M.Tech@PG@Phd@MBA@Other@B.Arch", max_length=100
            ),
        ),
        migrations.AlterField(
            model_name="notifications",
            name="year",
            field=models.CharField(default="11111", max_length=100),
        ),
    ]
