# Generated by Django 4.1.6 on 2023-12-04 10:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api2", "0034_alter_datinguser_posted_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datinguser",
            name="posted_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 4, 10, 4, 22, 894452)
            ),
        ),
    ]
