<<<<<<< HEAD
# Generated by Django 4.1.6 on 2023-12-18 16:55
=======
# Generated by Django 4.1.6 on 2023-12-18 14:34
>>>>>>> 2f17aea9dee129e0b45bddf6211310cc2c0ce0fc

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
<<<<<<< HEAD
        ("api2", "0037_alter_datinguser_posted_date"),
=======
        ('api2', '0037_alter_datinguser_posted_date'),
>>>>>>> 2f17aea9dee129e0b45bddf6211310cc2c0ce0fc
    ]

    operations = [
        migrations.AlterField(
<<<<<<< HEAD
            model_name="datinguser",
            name="posted_date",
            field=models.DateTimeField(
                default=datetime.datetime(2023, 12, 18, 16, 55, 41, 930908)
            ),
=======
            model_name='datinguser',
            name='posted_date',
            field=models.DateTimeField(default=datetime.datetime(2023, 12, 18, 14, 34, 16, 124986)),
>>>>>>> 2f17aea9dee129e0b45bddf6211310cc2c0ce0fc
        ),
    ]
