<<<<<<< HEAD
# Generated by Django 4.1.6 on 2023-12-21 15:56
=======
# Generated by Django 4.1.6 on 2023-12-18 14:34
>>>>>>> 54b0841fe11c85bc61f8071f478f64cc55fd412f

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("api2", "0037_alter_datinguser_posted_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="datinguser",
            name="posted_date",
            field=models.DateTimeField(
<<<<<<< HEAD
                default=datetime.datetime(2023, 12, 21, 15, 56, 31, 336776)
=======
                default=datetime.datetime(2023, 12, 18, 14, 34, 16, 124986)
>>>>>>> 54b0841fe11c85bc61f8071f478f64cc55fd412f
            ),
        ),
    ]
