# Generated by Django 4.1.6 on 2024-02-16 14:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api2', '0044_alter_datinguser_posted_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datinguser',
            name='posted_date',
            field=models.DateTimeField(default=datetime.datetime(2024, 2, 16, 14, 58, 27, 932491)),
        ),
    ]
